[desktop]
preview_url = 'https://de.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{PLACEHOLDER}}'
campaign_tracking='00-ba-200416'

[desktop.banners.ctrl]
pagename = "B20_WMDE_Test_05_ctrl"

[desktop.banners.var]
pagename = "B20_WMDE_Test_05_var"

[desktop.test_matrix]
platform = [ "edge",
            "firefox_win10", "chrome_win10",
            "safari",
            "firefox_macos", "chrome_macos",
            "firefox_linux", "chrome_linux"
            ]

resolution = [
    "800x600",
    "1024x768",
    "1280x960",
    "1600x1200",
    "1920x1200",
    "2560x1440"
]

[test]
preview_url = 'https://de.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{PLACEHOLDER}}'
campaign_tracking='00-test-200416'

[test.banners.ctrl]
pagename = "B20_WMDE_Test_05_ctrl"


[test.test_matrix]
platform = ["firefox_macos", "chrome_linux" ]
resolution = ["1024x768"]


[mobile]
preview_url = 'https://de.m.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{PLACEHOLDER}}'
campaign_tracking='00-mobile-200416'

[mobile.banners.ctrl]
pagename = "B20_WMDE_Test_Mobile"

[mobile.test_matrix]
device = [
    "samsung_s6",
    'pixel_3',
    'pixel_6a',
    'pixel_8',
    "iphone_8",
    "iphone_13_mini",
    "iphone_15",
    "iphone_16",
    "ipad_pro_9_7_inch",
    "ipad"
]
orientation = ["portrait", "landscape"]



[mobile_test]
preview_url = 'https://de.m.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{PLACEHOLDER}}'
campaign_tracking='00-mobile-test-200416'

[mobile_test.banners.ctrl]
pagename = "B20_WMDE_Test_Mobile"

[mobile_test.test_matrix]
device = [
    "samsung_s6",
]
orientation = ["landscape", "portrait"]
