[desktop]
preview_url = 'https://de.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{PLACEHOLDER}}'
campaign_tracking='00-ba-200416'

[desktop.banners.ctrl]
pagename = "B20_WMDE_Test_Desktop"

[desktop.test_matrix]
operating_system = ["win10", "win7", "macos", "linux"]
browser = ["edge", "ie11", "firefox", "safari", "chrome"]
resolution = [ "1024x768", "1280x960"]

[test]
preview_url = 'https://de.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{PLACEHOLDER}}'
campaign_tracking='00-test-200416'

[test.banners.ctrl]
pagename = "B20_WMDE_Test_Desktop"

[test.test_matrix]
operating_system = ["win10", "win7" ]
browser = [ "edge", "ie11", "firefox", "safari", "chrome"]
resolution = ["1280x960"]


[mobile]
preview_url = 'https://de.m.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{PLACEHOLDER}}'
campaign_tracking='00-mobile-200416'

[mobile.banners.ctrl]
pagename = "B20_WMDE_Test_Mobile"

[mobile.test_matrix]
device = ["iphone_xs_max", "iphone_5s", "samsung_s6", "samsung_s9_plus"]
orientation = ["portrait"]