[desktop]
preview_url = 'https://de.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{PLACEHOLDER}}'

[desktop.banners.ctrl]
pagename = "B19WMDE_21_191221_ctrl"

[desktop.banners.var]
pagename = "B19WMDE_21_191221_var"

[desktop.test_matrix]
operating_system = ["win10", "win7", "macos", "linux"]
browser = ["edge", "ie11", "firefox", "safari", "chrome"]
resolution = ["1024x768", "1280x960"]

[mobile]
preview_url = 'https://de.m.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{PLACEHOLDER}}'

[mobile.banners.ctrl]
pagename = "B19WMDE_21_191221_ctrl"

[mobile.banners.var]
pagename = "B19WMDE_21_191221_var"

[mobile.test_matrix]
device = ["iphone_xs_max", "iphone_se", "iphone_se", "samsung_s9"]
orientation = ["portrait", "landscape"]